### PR TITLE
enkf_job_scale_std_correlated uses only realizations with data

### LINKED ISSUE #389: Fix bug  in workflow job enkf_job_scale_std_correlated:
This trace-back/bug comes from a situtation where some realisations have failed and there is missing data. We must be more robust to that in the function:  `enkf_main_std_scale_correlated_obs_JOB()`

```txt
Abort called from: __hash_get_node (/var/jenkins/jenkins-be/workspace/komodo/cache/libecl-master/lib/util/hash.cpp:90)

Error message: __hash_get_node: tried to get from key:WOPT:A-16HP.115 which does not exist - aborting



--------------------------------------------------------------------------------
 #00 util_abort__(..)                                                              in ??:0
 #01 ???(..)                                                                       in hash.cpp:0
 #02 hash_get(..)                                                                  in ??:0
 #03 block_fs_fread_realloc_buffer(..)                                             in ??:0
 #04 ???(..)                                                                       in block_fs_driver.cpp:0
 #05 ???(..)                                                                       in enkf_node.cpp:0
 #06 enkf_obs_get_obs_and_measure_node(..)                                         in ??:0
 #07 enkf_obs_get_obs_and_measure_data(..)                                         in ??:0
 #08 enkf_obs_scale_correlated_std(..)                                             in ??:0
 #09 enkf_main_std_scale_correlated_obs_JOB(..)                                    in ??:0
 #10 ffi_call_unix64(..)                                                           in /var/jenkins/jenkins-be/workspace/komodo/cache/Python-2.7.14/Modules/_ctypes/libffi/src/x86/unix64.S:79
 #11 ffi_call(..)                                                                  in /var/jenkins/jenkins-be/workspace/komodo/cache/Python-2.7.14/Modules/_ctypes/libffi/src/x86/ffi64.c:527
```

### PR DESCRIPTION
**Pull request by andreabrambilla**
Previously all the realizations were used and this lead to a crash when a realization with no data was encountered

closes #389

**Pre un-WIP checklist**
- [x] Statoil tests pass locally
- [x] Have completed graphical integration test steps

### CODE REVIEW

File: lib/enkf/enkf_main_jobs.cpp [hunk 1]
```diff
@@ -505,10 +507,14 @@ void * enkf_main_std_scale_correlated_obs_JOB(void * self, const stringlist_type
     int ensemble_size                       = enkf_main_get_ensemble_size(enkf_main);
     enkf_fs_type * fs                       = enkf_main_job_get_fs( enkf_main );
     enkf_obs_type * obs                     = enkf_main_get_obs( enkf_main );
-    int_vector_type * realizations          = int_vector_alloc(1, 0);
     local_obsdata_type * obsdata = local_obsdata_alloc( "OBS-JOB" );
 
-    int_vector_init_range(realizations, 0, ensemble_size, 1);
+    // Find out what realizations have data
+    auto const* state_map = enkf_fs_get_state_map(fs);
+    assert(ensemble_size == state_map_get_size(state_map));
```
Comment (joakim-hove) [inline lib/enkf/enkf_main_jobs.cpp]: This `assert` is not required; we will just infer the interesting/relevant size from the `state_map`.

File: lib/enkf/enkf_main_jobs.cpp [hunk 2]
```diff
@@ -505,10 +507,14 @@ void * enkf_main_std_scale_correlated_obs_JOB(void * self, const stringlist_type
...
+    auto* has_data_mask = bool_vector_alloc(ensemble_size, false);
```
Comment (joakim-hove) [inline lib/enkf/enkf_main_jobs.cpp]: Better to just allocate size 0 - it will automatically grow to the correct size in the `state_map_select_matching()` function.

File: lib/enkf/enkf_main_jobs.cpp [hunk 3]
```diff
@@ -505,10 +507,14 @@ void * enkf_main_std_scale_correlated_obs_JOB(void * self, const stringlist_type
     int ensemble_size                       = enkf_main_get_ensemble_size(enkf_main);
     enkf_fs_type * fs                       = enkf_main_job_get_fs( enkf_main );
     enkf_obs_type * obs                     = enkf_main_get_obs( enkf_main );
-    int_vector_type * realizations          = int_vector_alloc(1, 0);
     local_obsdata_type * obsdata = local_obsdata_alloc( "OBS-JOB" );
 
-    int_vector_init_range(realizations, 0, ensemble_size, 1);
+    // Find out what realizations have data
+    auto const* state_map = enkf_fs_get_state_map(fs);
```
Comment (joakim-hove) [inline lib/enkf/enkf_main_jobs.cpp]: I consider `const` to be more important information than `auto` - and would prefer the "east const" variety: `const auto`-

File: lib/enkf/enkf_main_jobs.cpp [hunk 4]
```diff
@@ -505,10 +507,14 @@ void * enkf_main_std_scale_correlated_obs_JOB(void * self, const stringlist_type
...
+    assert(ensemble_size == state_map_get_size(state_map));
+    auto* has_data_mask = bool_vector_alloc(ensemble_size, false);
+    state_map_select_matching(state_map, has_data_mask, STATE_HAS_DATA);
+    auto const* realizations = bool_vector_alloc_active_list(has_data_mask);
```
Comment (joakim-hove) [inline lib/enkf/enkf_main_jobs.cpp]: We are taking out first tumbling steps in the direction of C++ - but we still need to match up `xxx_alloc()` with `xxx_free()`  - i.e. both the `realizations` and the `has_data_mask` must be properly collected.

File: lib/enkf/state_map.cpp [hunk 5]
```diff
@@ -34,7 +34,7 @@
 struct state_map_struct {
   UTIL_TYPE_ID_DECLARATION;
   int_vector_type  * state;
-  pthread_rwlock_t   rw_lock;
+  pthread_rwlock_t mutable rw_lock;
```
Comment (joakim-hove) [inline lib/enkf/state_map.cpp:37]: The use `mutable` and `const state_map_type` was a very welcome change.

**Comment by andreabrambilla** [comment]
Comments addressed, should be pretty much ready now. Thanks for the review :+1:

**Review by joakim-hove — APPROVED** [review]
:-)
