### PR TITLE
Matrix size

### LINKED ISSUE #1131: New localisation functionality using row_scaling fails if grid size exceeds 62x62x62
Preliminary testing of row_scaling functionality fails if grid size exceeds 62x62x62. The error message (if not segmentation fault appear) is Size mismatch between row_scaling and A matrix.
[Test localisation using new functionality.pptx](https://github.com/equinor/libres/files/6178615/Test.localisation.using.new.functionality.pptx)

### PR DESCRIPTION
**Pull request by joakim-hove**
**Issue**
Part of #1069 Fixes: https://github.com/equinor/libres/issues/1131

**Approach**
Ensure that resizing of the A matrix works together with row scaling.

### CODE REVIEW

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Comment by ManInFez** [comment]
Test this please!

File: lib/enkf/enkf_main.cpp [hunk 1]
```diff
@@ -1139,11 +1139,17 @@ static void enkf_main_analysis_update( enkf_main_type * enkf_main ,
             for (int ikw=0; ikw < scaled_keys.size(); ikw++) {
               const auto& key = scaled_keys[ikw];
               const active_list_type * active_list = local_dataset_get_node_active_list(dataset, key.c_str());
+              const auto matrix_rows = matrix_get_rows(A);
+              const auto* config_node = ensemble_config_get_node(serialize_info->ensemble_config, key.c_str());
+              const auto node_size = enkf_config_node_get_data_size(config_node, serialize_info->report_step);
+              if (matrix_get_rows(A) < node_size)
+                  matrix_resize( A , node_size , active_ens_size , false);
```
Comment (ManInFez) [inline lib/enkf/enkf_main.cpp:1146]: Is the A matrix empty at this point?

Comment (joakim-hove) [reply lib/enkf/enkf_main.cpp:1146]: No - the matrix is created with a default size - variable `matrix_start_size` further up in the same function.

Comment (ManInFez) [reply lib/enkf/enkf_main.cpp:1146]: ok. But why is the A matrix resized and not the row_scaling?

**Comment by joakim-hove** [comment]
Rebased!

**Comment by ManInFez** [comment]
#1127 merged, needs a rebase :)

**Comment by joakim-hove** [comment]
rebased

File: tests/res/enkf/test_row_scaling_case.py [hunk 2]
```diff
@@ -458,3 +463,57 @@ def test_2ministep(self):
 
                     diff = abs(v1 - v2)
                     assert diff < 0.05
```
Comment (ManInFez) [inline tests/res/enkf/test_row_scaling_case.py]: This fails on python 3.9, why is it set to 0.05?

Comment (joakim-hove) [reply tests/res/enkf/test_row_scaling_case.py]: The problem here is that there is a stochastic element and the test is just "somewhat close" - 0.05 was OK on my machine. I realize this is an extremely weak test, but to actually get control over the random state to the level needed to get this identical is a quite large job.

I have increased the test ensemble size which should reduce fluctuations but of course also increase runtime; alternatively the actual numerical test can just be removed?

**Comment by ManInFez** [comment]
Test this please!

File: tests/res/enkf/test_row_scaling_case.py (hunk 2 above)
Comment (ManInFez) [reply tests/res/enkf/test_row_scaling_case.py]: I am worried that this flakyness will hit us at later point in time. Maybe it is best to remove it?

Comment (joakim-hove) [reply tests/res/enkf/test_row_scaling_case.py]: I don't agree with the term flakyness - the situation is understood; but I agree that the value is very limited - happy to remove it.

Comment (ManInFez) [reply tests/res/enkf/test_row_scaling_case.py]: It will not occasionally fail? or is it deterministic and will always fail on python 3.9? What does the it mean then; that the difference between one ministep and two ministeps is less than 5%?

Comment (joakim-hove) [reply tests/res/enkf/test_row_scaling_case.py]: No it will not occasionally fail; by setting the seed in the test the sampling is deterministic and will be reproducible. The difference comes from the function `obs_data_allocE`. Assume that we have a reproducible stream of random numbers:
```
R = {R_1, R_2, R_3, R_4, R_5, R_6}
``` 

then in the case of one ministep with two observations and three ensemble members we will get:
```
     [ R_1  R_2 ]
E =  [ R_3  R_4 ]
     [ R_5  R_6 ]
``` 
whereas we with two ministeps with one observation in each we get the two E matrices:
```
     [R_1]           [R_4] 
E1 = [R_2],     E2 = [R_5]     
     [R_3]           [R_6] 
```

i.e. because the the ensemble members and observations are interleaved in the E matrix 2 x 1 != 2.

I must admit I was little surprised by the Python 3.9 failure - my guess is/was that there has been some change in the Python random number functionality so we do not get the same sequence on 3.9 as on 3.8 - I  have not investigated that further.

> What does the it mean then; that the difference between one ministep and two ministeps is less than 5%?

That they are *quite close*; which is what we should expect. It should be added that the difference is not 5% - the comparison is absolute.

Comment (ManInFez) [reply tests/res/enkf/test_row_scaling_case.py]: Would it be possible to attach a mocked random number generator to the enkf_main object before creating E which would then create? 
```
     [R_1]           [R_4] 
E1 = [R_2],     E2 = [R_5]     
     [R_3]           [R_6] 

     [ R_1  R_4 ]
E =  [ R_2  R_5 ]
     [ R_3  R_6 ]

```

Comment (joakim-hove) [reply tests/res/enkf/test_row_scaling_case.py]: >Would it be possible to attach a mocked random number generator to the enkf_main object before creating E which would then create?

Everything is possible - but I would say: *No it is not worth it*. What you suggest would certainly be a necessary step - I have not verified if it whether it is sufficient, my guess is that additional changes would be necessary.

Comment (ManInFez) [reply tests/res/enkf/test_row_scaling_case.py]: Then I would say the numeric comparison is not having any value, and it can be removed. I guess the test only shows that it is possible to split up in multiple ministeps, but it is not identical to doing it in one step.

Comment (joakim-hove) [reply tests/res/enkf/test_row_scaling_case.py]: >  [...] and it can be removed

I agree. I have removed it - ans reset the test ensemble size to 10.

**Comment by ManInFez** [comment]
Test this please!

**Review by ManInFez — APPROVED** [review]
